[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
anchor_student_intro = "8hkDLDXHJpXwEufzpUtWp5WhgVBvfoywcXApnpDXTEk2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sebatustra/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
