[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_student_intro = "GztZcTBZTcv5DUwY6dRWgzFL5WhcNZ8Wx8zRSoLniXZM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sebatustra/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
